// Extracts Playwright's in-page InjectedScript source (selector engine + ariaSnapshot)
// from playwright-core's bundle and writes it to src/vendor/injected-script.ts.
// See GUIDANCE §3.3 and DECISIONS.md (vendoring over connectOverCDP). Re-run after bumping playwright-core.
const pkg = await Bun.file("node_modules/playwright-core/package.json").json();
const bundle = await Bun.file("node_modules/playwright-core/lib/coreBundle.js").text();
const marker = 'packages/playwright-core/src/generated/injectedScriptSource.ts"() {';
const at = bundle.indexOf(marker);
if (at < 0) throw new Error("injectedScriptSource marker not found in coreBundle.js");
const m = /\n\s*(source\d*) = '/g;
m.lastIndex = at;
const hit = m.exec(bundle);
if (!hit) throw new Error("source literal not found after marker");
let i = hit.index + hit[0].length; // first char inside the quote
const start = i - 1;
while (i < bundle.length) {
  const c = bundle[i];
  if (c === "\\") { i += 2; continue; }
  if (c === "'") break;
  i++;
}
const literal = bundle.slice(start, i + 1);
const source: string = new Function("return " + literal)();
const out = `// GENERATED by scripts/vendor-injected.ts from playwright-core@${pkg.version} — do not edit.
// Playwright's InjectedScript: selector engine (css=, text=, role=, xpath=, internal:* ...), ariaSnapshot, hit-testing.
export const playwrightVersion = ${JSON.stringify(pkg.version)};
export const injectedScriptSource: string = ${JSON.stringify(source)};
`;
await Bun.write("src/vendor/injected-script.ts", out);
console.log(`vendored injected script: ${source.length} chars from playwright-core@${pkg.version}`);
